new folder and hw file from lesson 16
eugene-okulik/Azamat pull request #15
Opened 2024-10-28 16:43 UTC by Azamattm

2024-10-28 17:00 UTC, Azamattm commented
Линтер меня кошмарит =) Сделал знатный костыль на мое мнение, но никак не пока не могу дойти до более красивого решения

2024-10-28 17:01 UTC, Azamattm commented
Линтер с отступами меня кошмарит =) Сделал знатный костыль на мое мнение, но никак не могу дойти пока до красивого решения

2024-10-29 08:10 UTC, eugene-okulik requested changes
Прямое решение в том, чтобы пытаться запрашивать из базы данные из каждой строки файла. Если такое нашлось, значит в базе это есть. Если не нашлось, значит в базе этого нет.

2024-10-29 08:10 UTC, eugene-okulik commented on homework/azamat_far/lesson_16_azamat/hw_16.py
> +\\data.csv', newline='') as csv_file:
У меня не отрабатывает. На моем компе нет диска F

2024-10-29 08:10 UTC, eugene-okulik commented on homework/azamat_far/lesson_16_azamat/hw_16.py
> +WHERE s.name = 'Ivan' or s.name = 'Petr' or s.name = 'Mark'""")
А если я изменю файл с данными и там появится еще John?

2024-10-29 19:16 UTC, Azamattm commented
Сори, забыл убрать хардкод пути до файла

2024-10-30 12:59 UTC, eugene-okulik approved these changes
Да, примерно так, но подстановки лучше всегда использовать защищенные, это те, которые `%s`  
  
Вот и добрались мы до конца раздела по питону. Теперь сделаем отчетную работу по нему.  
Если будут вопросы по следующему заданию - пиши в телеграм

2024-10-30 12:59 UTC, merged