Homework 5 added folder and three tasks py files
eugene-okulik/Azamat pull request #4
Opened 2024-03-24 11:41 UTC by Azamattm

Homework 5

2024-03-24 12:06 UTC, eugene-okulik requested changes

2024-03-24 12:06 UTC, eugene-okulik commented on homework/azamat_far/lesson_5_azamat/task_1.py
> +)
В занятии я показывал, что распаковка делается сильно проще

2024-03-24 12:06 UTC, eugene-okulik commented on homework/azamat_far/lesson_5_azamat/task_2.py
> +num_result_1 = int(result_1[result_1.index("42"):])
Если еще в момент написания программы мы знаем, что в строке будет число 42, то мы можем написать просто print(42 + 10)  
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов пере числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-03-24 12:06 UTC, eugene-okulik commented on homework/azamat_far/lesson_5_azamat/task_3.py
> +study these subjects: {second_str_1}, {second_str_2}, {second_str_3}")
В занятии я показывал как превращать списки в строки. `join` - то, что пригодится тебе в этом задании.

2024-03-24 18:23 UTC, Azamattm reviewed
Fixed task 1, task 2, task 3

2024-03-24 18:27 UTC, Azamattm reviewed
Fixed tasks 1, 2, 3

2024-03-25 06:22 UTC, eugene-okulik approved these changes

2024-03-25 06:22 UTC, merged